### ISSUE TITLE
Dataset size

### ISSUE THREAD

**Issue by salva-u** [UBC-MDS/522-workflows-group-18#10]
Our dataset is larger than 100 MB so we need an alternative plan on how to approach the create data/ dir instruction. For now I have asked tiff what we can do instead. Please suggest if you think we can use a subset or we should try and just reference the link of dataset that can be downloaded by others.

**Comment by atabak-alishiri** [comment]
I started working on data with the direct link, but I think we should wait for a response from tiff.

**Comment by salva-u** [comment]
This is the error we get when using Git Large File Storage "Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to push some refs to 'https://github.com/UBC-MDS/522-workflows-group-18.git'"

**Comment by farrandi** [comment]
A temporary solution was made by cutting down the dataset. 

I am closing the issue.
