### ISSUE TITLE
Change repository name

### ISSUE THREAD

**Issue by farrandi** [UBC-MDS/522-workflows-group-18#111]
- Idea to change the repository name to `english_score_predictor`
- Might do it after Milestone 4

**Comment by atabak-alishiri** [comment]
> * Idea to change the repository name to `english_score_predictor`
> * Might do it after Milestone 4

I agree with the name, do you know what might be affected by the repo name? @farrandi

**Comment by farrandi** [comment]
Hmmm, I guess:
1. The repo link itself
2. the Report github pages link
3. I would have to change the dockerhub name to match

That is all I can currently think of.
