### ISSUE TITLE
Clean up of main analysis file 

### ISSUE THREAD

**Issue by salva-u** [UBC-MDS/522-workflows-group-18#26]
1. Intro - summary @rbouwer 
2. Intro Method + Results: @salva-u 
3. Intro - Background: @atabak-alishiri 
4. Dataset : @salva-u @atabak-alishiri 
5. Change file names in src folder: @rbouwer 
6. References: @rbouwer @farrandi  @atabak-alishiri  @salva-u  ( APA citations)
7. EDA clean up the code part: @atabak-alishiri @salva-u 
8. Create release of the final branch: @farrandi 
9. Update the environment.yml: @rbouwer (if needed/double check)
10. Final submission can be done by @atabak-alishiri

**Comment by rbouwer** [comment]
- Change file names in src folder: @rbouwer

I was thinking I should wait to do this until right before we submit to avoid any issues with naming differences

**Comment by rbouwer** [comment]
Intro - summary @rbouwer -> @atabak-alishiri to review and input
