### ISSUE TITLE
Week 4 Improvements

### ISSUE THREAD

**Issue by rbouwer** [UBC-MDS/522-workflows-group-18#58]
- [X] fix drop features (unwanted columns) before preprocessing/eda (https://github.com/UBC-MDS/522-workflows-group-18/pull/47)
- [ ] include DummyRegressor() base model
- [ ] try non-linear regression models/feature engineering (e.g. Polynomial Features, KNN (and standardize data), etc.)
- [x] report multiple metrics for models
- [ ] transform target (e.g. log transform)

**Comment by rbouwer** [comment]
LOG: 

- [X] updated last (plotting) function
- [X] update second last (coefficient) function

**Comment by salva-u** [comment]
Based on feedback from Milestone 1, we should update our usage instructions to be more explicit, I assume, since some commands did not work for tiff

**Comment by salva-u** [comment]
Add creative commons license

**Comment by salva-u** [comment]
Since the project has been broken down into scripts and the goal is to learn about reproducible analysis, we have opted to not include improving model and log transforming the prediction model in the interest of time, all other points have been addressed.
