### ISSUE TITLE
script to take data, outputting a sample and split into train and test

### ISSUE THREAD

**Issue by atabak-alishiri** [UBC-MDS/522-workflows-group-18#59]

**Comment by farrandi** [comment]
@atabak-alishiri @salva-u Can you also output the `X_train_enc` column names to a file

Update: Not needed, @rbouwer's update to her function makes it so that I do not need it anymore

**Comment by salva-u** [comment]
Great noted.

**Comment by atabak-alishiri** [comment]
here is the command to run the script:
`python src/english_score_get_data.py --url=https://osf.io/download/g72pq/ --output_folder_path=./data/raw`
