### ISSUE TITLE
Folder Restructuring

### ISSUE THREAD

**Issue by salva-u** [UBC-MDS/522-workflows-group-18#62]
Inside our `src/` dir can we move all our script files into `src/scripts/` and the helper functions into `src/helper/`

**Comment by farrandi** [comment]
we could leave our script in `src` and the helper functions in `src/helper`

**Comment by salva-u** [comment]
sure works for me, but just thought we could do with a `scripts` folder since that is in the sample tiff has. I am okay with both though

**Comment by farrandi** [comment]
Discussed offline and decided to: scripts to`src/scripts/` and the helper functions into `src/helper/`
