### ISSUE TITLE
Large File Discussion

### ISSUE THREAD

**Issue by rbouwer** [UBC-MDS/522-workflows-group-18#66]
@atabak-alishiri to try large file handling to try and keep source data, training data, and test data
- if not able to -> keep only training and test data 
- try zipping data file(s) to see if there are improvements

**Comment by atabak-alishiri** [comment]
Zipping reduced the file size from 83 MB to around 10 MB. So I am going to try this method first

**Comment by salva-u** [comment]
fixed, we can close this

**Comment by salva-u** [comment]
resolved by zipping
