### ISSUE TITLE
Update environment and docker to include new issues at Week 3

### ISSUE THREAD

**Issue by farrandi** [UBC-MDS/522-workflows-group-18#71]
- click
- pickle
- dataframe-image

+ update README for this

@salva-u can you tell me the versions for pickle and dataframe-image

**Comment by salva-u** [comment]
dataframe-image 0.2.2
pickleshare 0.7.5

**Comment by rbouwer** [comment]
@farrandi could you please update the environment file to include   `- jupyter_contrib_nbextensions=0.7.0`

**Comment by farrandi** [comment]
Updated environment based on PRS #77 and #64.

Still need to do docker, will make a new branch from main later.

+ Also need to set up github actions, should I make a new issue for that?

**Comment by salva-u** [comment]
@farrandi in the 61-eda branch , we need to update the environment file, the altair package is not installing , maybe some issue with the way versioning is done ?

**Comment by salva-u** [comment]
nevermind was using wrong command, works now

**Comment by rbouwer** [comment]
Hey @farrandi, could you add myst-nb 1.0.0 please?

**Comment by rbouwer** [comment]
Sorry again - could you also add jupyter-book : 0.15.1
