### ISSUE TITLE
Plotting Issues

### ISSUE THREAD

**Issue by salva-u** [UBC-MDS/522-workflows-group-18#72]
Comment issues that we need to fix with figures

**Comment by salva-u** [comment]
Add a title EDA numeric plot , categorical plot

**Comment by salva-u** [comment]
Actual vs Predicted , issue with overplotting could be changed.

**Comment by salva-u** [comment]
numeric and categorical plots will not be added to final report because they are part of eda

**Comment by rbouwer** [comment]
Will fix overplotting of actual vs. predicted in week 4 after trying to improve the model https://github.com/UBC-MDS/522-workflows-group-18/issues/58
