### ISSUE TITLE
Logging Changes Made

### ISSUE THREAD

**Issue by salva-u** [UBC-MDS/522-workflows-group-18#94]
Docker:
1. Uploaded to docker hub 
2. Instead of manual conda install --> we use conda environment conda file 

Helper Functions:
1. Fix `show_feat_coeff.py` and `plot_regr_pred.py` functions and corresponding test files:
    plot_regr_pred: 402094b8f906e4f92f0cd9ec749b27f19481eafd
        -Fixed return to be Axes object and added unittest rather than pytest
    show_feat_coeff: b9a06f5875ca940933eeb148d9a5aa6dd6568d55
        -Fixed return to get feature names out from X_train rather than X_enc and added unittest rather than pytest
        -Also adjusted parameters for FunctionTransformer (feature_names_out='one-to-one") so that we could get all feature names

Data Download and EDA:
1. We fixed dropping of some additional question level columns that wouldn't be used in the analysis but were being dropped outside the transformer. 
2.

**Comment by atabak-alishiri** [comment]
fixed the download script to work from the root: 2594269
fixing the transformer dropping outside of the transformer: 1352860

**Comment by atabak-alishiri** [comment]
### References
- In background section, you mentioned "Various studies have explored a range of determinants, including age, educational background, language exposure, and the presence of learning disabilities like dyslexia", so I think you'd better include the references of these studies. (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841652067): [908b58a](https://github.com/UBC-MDS/522-workflows-group-18/pull/101/commits/908b58a4099f6f096f24eae080992fc74165ae95) and [c476b28](https://github.com/UBC-MDS/522-workflows-group-18/pull/101/commits/c476b28c8e5e79e7187c707f4e85415da07485ca)

### License
- License from PMC (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1839733677): [18b36c4](https://github.com/UBC-MDS/522-workflows-group-18/pull/99/commits/18b36c4ffed23ca2d4e8848275de6c9f1dd5e417)
- The licence should include both the MIT licence and licence of the dataset being analyzed. (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841172058): [18b36c4](https://github.com/UBC-MDS/522-workflows-group-18/pull/99/commits/18b36c4ffed23ca2d4e8848275de6c9f1dd5e417)
