### ISSUE TITLE
Feedback from Peer Review

### ISSUE THREAD

**Issue by salva-u** [UBC-MDS/522-workflows-group-18#96]
- Mention we do not need license for Open Data/Public Dataset " @atabak-alishiri  @farrandi 
For the license part, I did a little bit research, your database and also article that use this database is funded by some organization and put it as the free PMC (PubMedCentral) article, which freely available for public, and I found the disclaimer on this "https://pubmed.ncbi.nlm.nih.gov/disclaimer/". I don't know how to correctly provided it in license.md, may be you create a section for the data you used and specify the disclaimer of free PMC over there (or better ask tiff on how exactly you should do this)."
-put your names as authors under your project name in the report. @rbouwer 
- hide the imports @rbouwer 
- add some EDA plots to the report to show distribution by target @rbouwer 
- make the plots look better and add some writing to go around it @salva-u 
- Separate Limitations to a new header  @rbouwer 
- Address this "In README.md about the paragraph is concatenate in github, you should split it.(I understand that it will cause from error on markdown, may be you should give it two extra white line to separate it)" @farrandi 
- Add makefile or sth to make tests easy to run (move the tests imports to correct folder) @farrandi 
- Reword this because you do not reference these studies ""Various studies have explored a range of determinants, including age, educational background, language exposure, and the presence of learning disabilities like dyslexia"
- Insertion error in report "Some variable insertion errors: "suggesting a % average prediction error." in method and results section in the report; "RMSE scores and fit times ({numref}lasso_top_models-fig)." for figure 3."
- Figure 4 is too small compare to other figures, and the text looks blur because of low resolution.
- Fix the typos in the report 
- Change color scheme of correlation matrix 
- Fix the results plot "Regarding Fig. 5, it would be interesting if you discussed more about why there seems to be a straight line acting as a boundary on the upper right-hand side of your scatterplot. Also, the graph seem a little bit crowded, it would probably be better if you made it a little bit bigger and if you made the dots more translucent or changed the color scheme to one that allow us to see the density (how crowded) of different sections of the plot (maybe a 2-D histogram would be better)."

**Comment by rbouwer** [comment]
# Comments From Peer Review to Address
**REMEMBER TO LOG CHANGES/IMPROVEMENTS IN CHANGE LOG: https://github.com/UBC-MDS/522-workflows-group-18/pull/95**
## License
### @atabak-alishiri 
- License from PMC (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1839733677)
- The licence should include both the MIT licence and licence of the dataset being analyzed. (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841172058)
## README
### @farrandi 
- Add contact channel (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1839733677)
- Format README about paragraph (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1839733677) (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841652067)
## Authors
### @rbouwer 
- Put names as authors under our project name in the report (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1839733677) (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841172058)
## Imports at Top of Report
### @rbouwer 
- The code chunk of dependencies employed for the analyses should be hidden (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841172058)
## Introduction
- Add usage of analysis to intro (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1839733677)
## EDA
### @salva-u (to make improvements and add wordage) @rbouwer (to incorporate into report)
- Include some visualizations of the distributions (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1839733677) (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841172058) (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1842005496 - number 6 & 7)
- May be not best practice to include EDA files we don't include in the report (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841652067)
- Fix correlation matrix color scheme (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1842005496)
## Results / Discussion
### @rbouwer 
- Separate limitations as separate subsection (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1839733677)
- Fix/clarify the actual vs. predicted plots (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1842005496)
## Tests
### @farrandi 
- Automation of testing (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841172058) (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1842005496 - number 2 [fix path to src/helper])
## References
### @atabak-alishiri 
- In background section, you mentioned "Various studies have explored a range of determinants, including age, educational background, language exposure, and the presence of learning disabilities like dyslexia", so I think you'd better include the references of these studies. (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841652067)
## Overall Improvements 
- Add additional scoring metrics @salva-u 
- Model improvements / feature engineering to increase score (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841172058) @salva-u
- Variable insertion errors (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841652067) @rbouwer
- Increase size of figure 4 (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841652067) @rbouwer 
- Typos (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1841652067 - number 7) (https://github.com/UBC-MDS/data-analysis-review-2023/issues/14#issuecomment-1842005496 - number 1) @rbouwer

**Comment by salva-u** [comment]
for EDA added the incorporation into notebook already @rbouwer to make it easier, let me know if more changes are needed

"@salva-u (to make improvements and add wordage) @rbouwer (to incorporate into report)"

**Comment by salva-u** [comment]
all points addressed and logged in change log
